### ISSUE TITLE
Feature request: Allow importing all assertions optionally?

### ISSUE THREAD

**Issue by tannerlyons** [webfront-toolkit/offensive.js#2]
Hey - this is awesome work and I love using it!

One thing I find when I'm using it in node is that I don't really care as much about bundle size and really just want the full suite.

In these cases I just import all assertions in some main portion of my app and call it good. 

I think this could be pretty easy (and optionall) allowed by adding an index file in `src/assertions/` that imports all of the assertion directories?

**Comment by mchalapuk** [comment]
Hello @tannerlyons,

Thanks for the suggestion. Feel free to create a PR with `assertions/index.ts` and some docs on this in `README.md`.

**Comment by tannerlyons** [comment]
I started working on this a bit and using the project in vanilla js it worked perfectly 👍🏻 which is what I've been doing thus far. 

However when testing in a typescript project I found some issues:

The following is what I could find as the minimal amount of code to run (before my change):

```
import check from "offensive";
import "offensive/assertions/aBoolean"; // removing this fails the ts compile
import "offensive/assertions/aBoolean/register"; // removing this fails at runtime, but compiles  (💯 spooky 👻)

check(true, "checker").aBoolean(); // note the lack of `is` from the builder
```

To add typings for the builder, I had to also include:
```
import "offensive/connectors";
```

and now this works:

```
import check from "offensive";
import "offensive/connectors";
import "offensive/assertions/aBoolean";
import "offensive/assertions/aBoolean/register";

check(true, "checker").is.aBoolean();
```

I think this is because the `assertions/X/register` files don't export any types, but they do the work at runtime.
And the `assertions/X/index` add the typings to the `AssertionBuilder`
I didn't dive into why the AssertionBuilder isn't imported until you import the connectors index...

**Comment by mchalapuk** [comment]
When using typescript, it's easiest to add include `node_modules/offensive/**/*.ts` in `tsconfig.json`. README lacks this information.

I think it would be best to discuss any issues in the review process.

**Comment by mchalapuk** [comment]
@tannerlyons You were right about the register file not exporting any types. Sorry, I didn't understand at the time. This became a problem since TypeScript 3 I think.

I fixed it in the latest version.

**Comment by mchalapuk** [comment]
Added `offensive/all` that preloads all assertions in version `2.8.0`.
